### ISSUE TITLE
Remove dot in opcodes

### ISSUE THREAD

**Issue by Kroc** [slu4coder/Minimal-64x4-Home-Computer#1]
I observed that where a dot is included in an opcode to purely separate `A = A ? B` forms vs. `B = B ? A` forms (that is, accumulator as destination vs. accumulator as source) that these would read more naturally if the destination indicator was put first just as it is implied to be accumulator in non-dotted opcodes, e.g. `ANZ: A = A & Z` but `AN.Z` would be `ZAN: Z = Z & A`. Since the type comes first, I have observed only the following letters used currently in dotted-opcodes: B, L, R, T & Z. **Because there are no current opcodes beginning with B, T or Z, and the dotted-opcodes for L & R would not conflict when swapped in this manner, there would be no name conflicts and all 256 opcodes would fit into 3 letters!**

**Comment by slu4coder** [comment]
Thanks for digging into this. Dot instructions are converted to non-dot instructions internally just as you have proposed, i. e. AN.Z is first translated into ZAN and only then assembled. You might as well (whatever you like more) use ZAN as an opcode in your sources. I personally prefer the dot notation since it exposes the general function of an instruction at the start of the mnemonic.
