### ISSUE TITLE
Resistor watts?

### ISSUE THREAD

**Issue by joelburton** [slu4coder/Minimal-64x4-Home-Computer#7]
The BOM lists 0.6W resistors, but it's a lot easier to find 0.5W ones that fit well with the very tight spacing on the PCB. Would 0.5W work?

Thanks!

**Comment by slu4coder** [comment]
That should not be a problem.

**Comment by nateo87** [comment]
Follow-up question - is even 0.5w rated resistors strictly necessary? I'm using 1/4w resistors in mine (which I'm currently having keyboard issues with).

**Comment by slu4coder** [comment]
Let's do the math. The resistors seeing the highest load are the 470 Ohm resistors in the VGA circuit, since they potentially have a voltage of 5V across them. Let's assume they see the full load 100% of the time (which they don't). Using Ohm's law I = U/R, it follows that the maximum current through these resistors is ~10mA. By using P = U*I we have P_max = 50mW. If you are using 1/4W rated resistors that mean your P_max is 250mW. There are smaller resistors present in the circuit but they do not see 5V. Please open a new discussion if you want to reach out for help concerning a potential keyboard issue.
